# Generated by Django 5.2.10 on 2026-01-24 12:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='E.g., Ground Floor, Balcony', max_length=50, unique=True)),
                ('number', models.IntegerField(default=0, help_text='Ordering for display')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Floor',
                'verbose_name_plural': 'Floors',
                'ordering': ['number', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('table_number', models.CharField(help_text='Unique Table Identifier, e.g., T-01', max_length=20, unique=True)),
                ('name', models.CharField(blank=True, help_text='Friendly name, e.g., Window Seat', max_length=50)),
                ('capacity', models.PositiveIntegerField(default=2, help_text='Number of seats', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('dirty', 'Dirty/Cleaning')], default='available', max_length=20)),
                ('shape', models.CharField(choices=[('square', 'Square'), ('circle', 'Circle'), ('rectangle', 'Rectangle')], default='square', help_text='Shape for UI representation', max_length=20)),
                ('x_position', models.IntegerField(default=0)),
                ('y_position', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=100)),
                ('height', models.IntegerField(default=100)),
                ('qr_code_url', models.URLField(blank=True, null=True)),
                ('token', models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='tables.floor')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'ordering': ['floor__number', 'table_number'],
            },
        ),
    ]
