# Generated by Django 5.2.10 on 2026-01-24 13:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POSSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('starting_cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('closing_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('session_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'POS Session',
                'verbose_name_plural': 'POS Sessions',
                'ordering': ['-start_time'],
            },
        ),
    ]
