# Generated by Django 5.2.10 on 2026-01-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='possession',
            name='total_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='possession',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
