# Generated by Django 5.2.10 on 2026-01-24 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_sessions', '0002_possession_total_orders_possession_total_sales'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='possession',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='tables.floor'),
        ),
    ]
