# Generated by Django 5.2.10 on 2026-01-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CafeImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='cafe/branding/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CafeSettings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Our Cafe', max_length=100)),
                ('self_ordering_enabled', models.BooleanField(default=True)),
                ('order_type', models.CharField(choices=[('online', 'Online'), ('qr_menu', 'QR Menu Only')], default='online', max_length=20)),
                ('background_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('payment_at_counter', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cafe Settings',
                'verbose_name_plural': 'Cafe Settings',
            },
        ),
    ]
