# Generated by Django 5.2.10 on 2026-01-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafesettings',
            name='frontend_url',
            field=models.URLField(blank=True, help_text='Base URL for QR codes (e.g., https://your-ngrok.app)', max_length=255, null=True),
        ),
    ]
