# Generated by Django 5.2.10 on 2026-01-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('ready', 'Ready')], default='pending', max_length=20),
        ),
    ]
