# Generated by Django 5.2.10 on 2026-01-24 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#000000', help_text='Hex color code', max_length=20)),
                ('sequence', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['sequence', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_rate', models.DecimalField(choices=[(5.0, '5%'), (12.0, '12%'), (18.0, '18%'), (28.0, '28%')], decimal_places=2, default=5.0, max_digits=5)),
                ('uom', models.CharField(default='Unit', help_text='Unit of Measure (e.g., Unit, KG, Liter)', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('has_variants', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='menu.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('attribute', models.CharField(help_text='e.g., Size, Pack', max_length=100)),
                ('value', models.CharField(help_text='e.g., Small, Large, 6 pieces', max_length=100)),
                ('unit', models.CharField(blank=True, help_text='e.g., KG, Liter', max_length=50)),
                ('extra_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='menu.product')),
            ],
            options={
                'ordering': ['attribute', 'value'],
            },
        ),
    ]
