# Generated by Django 5.2.10 on 2026-01-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_code',
            field=models.CharField(blank=True, help_text='Auto-generated code for staff (e.g., POS-001)', max_length=20, null=True, unique=True),
        ),
    ]
