# Generated by Django 5.2.10 on 2026-01-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cashier_upi',
            field=models.CharField(blank=True, help_text='UPI ID of the cashier who processed this', max_length=100),
        ),
    ]
