# Generated by Django 5.2.10 on 2026-01-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_cashier_upi'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code identifier (e.g., razorpay, cash, upi)', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='External payment gateway transaction ID (Razorpay payment_id, etc.)', max_length=100, null=True, unique=True),
        ),
    ]
